### ISSUE TITLE
Error: Camera not ready!

### ISSUE THREAD

**Issue by iandol** [jamesbutler01/Mymou#16]
Hi James,

Testing using new Samsung Tablets, after we run the first couple of trials, when we are trying to start the next trial the "start trial" grey button is not responsive (this is using the spatial response task). Looking in the console every time I click the button I get a camera error:

```
D/MyMouTaskManager: Waiting for trial to be started
D/ViewRootImpl@27bf756[TaskManager]: ViewPostIme pointer 0
D/ViewRootImpl@27bf756[TaskManager]: ViewPostIme pointer 1
D/MyMouTaskManager: onClickListener called for 0
D/MyMouTaskManager: resetTimer
D/MyMouTaskManager: takePhoto() called
D/MyMouCameraMain: Capture request started at152322_645
D/MyMouTaskManager: Error: Camera not ready!
```

Sometimes it starts after a while and other times it never starts a trial again (it is not entirely deterministic), locked on the "start trial" page. We didn't see this with our older tablets.

**Comment by iandol** [comment]
Step debugging shows `takingPhoto` in CameraMain.java remains true so new photo cannot be taken, which is why the go_cue fails to work. If you wait a long time, image finally becomes available and go_cue can be used... The simple fix for the moment is just turn camera off ;-)

**Comment by jamesbutler01** [comment]
I ran into the same problem last week during an install in Newcastle, and I think default Mymou settings use high camera resolution, which is a bug I need to fix. I would check in camera settings what the photo resolution is set to. It should be one of, if not the, lowest resolution. 

This means cameraSavePhoto then takes _ages_ to write the integer txt file used for the facial recognition to disk. Current configuration is intentionally to block a new trial from starting while previous photos are being written to disc as I was worried about subsequent calls and potentially not finishing the save process. 

I will limit maximum resolution that the camera will ever use, as I doubt people will ever want 1000s of high resolution selfies.

**Comment by iandol** [comment]
I can confirm setting resolution to lowest value seems to fix this. 

Wouldn't a better solution be to have an option to [not]save the txt file, as I do want some higher resolution pictures of the subject faces but not for face recognition (I set 720x720).

**Comment by iandol** [comment]
However if Mymou is being debugged, even the lowest resolution takes ~56secs:

```
D/MyMouTaskManager: Error: FaceRecog not instantiated
D/CameraSavePhoto: Face recog finished
D/FolderManager: getting /storage/emulated/0/Mymou/20191220/IntArrays
W/System: A resource failed to call release. 
D/MyMouTaskManager: dailyTimer called
D/MyMouTaskManager: dailyTimer disabling app
    Enabling appfalse
D/CameraSavePhoto: Int array savedf20191220_193855_957.txt
D/CameraSavePhoto: Integer array saved in 56776
```

Not sure why it takes so long, but another argument to optionally disable the text file saving?

**Comment by iandol** [comment]
As another issue what are these:

```
D/MyMouTaskManager: dailyTimer called
D/MyMouTaskManager: dailyTimer disabling app
    Enabling appfalse
D/MyMouTaskManager: dailyTimer called
D/MyMouTaskManager: dailyTimer enabling app
```

They make the screen go super dim; I have automatic startup/shutdown disabled...

**Comment by jamesbutler01** [comment]
Good point, i will add an option to disable text file saving. I think it's just much slower and inefficient compared to writing an image, which are very efficiently stored with lots of clever compression etc (hence difference in file sizes too). 

The screen going super dim is my attempt at power saving, switching the brightness to low when the go cue is on the screen. Pressing the go cue should then restore the brightness to full. This can still be seen clearly in our facility with no natural light, but maybe not ideal in other places. I will add an option to disable this feature.

**Comment by iandol** [comment]
Ok this seems a very useful feature, perhaps a preference to control the dimming level if possible?

**Comment by jamesbutler01** [comment]
All of this now implemented on master:

- Users can toggle integer text file saving on and off in camera settings
- Users can now toggle 'power saving' mode, where the screen automatically dims if a trial is not started for preferencesManager.dimscreentime duration (default = 10 minutes)
- Users can specify the amount the screen is dimmed when this happens
