### ISSUE TITLE
Improving trial timeout timer?

### ISSUE THREAD

**Issue by iandol** [jamesbutler01/Mymou#19]
Currently the timeout timer is initiated at the start of a trial, which means if you change any parameters that make the trial longer or shorter, then timeout from the response cue is variable too. Not sure if there is a clean solution to this (each task should call the timeout, rather than it being initiated before the task starts), but just thought I'd mention it.

**Comment by jamesbutler01** [comment]
The timer can be reset within task by using callback.resetTimer_(); which resets TaskManager's timer. This should be placed in all onClickListeners, but i think i got sloppy with this when generating lots of tasks. Or do you mean you'd like dynamic trial timers? At the moment the could be hacked by using handlers to repeatedly call callback.resetTimer without the need for onClick events

**Comment by iandol** [comment]
OK yes that solves the problem:

https://github.com/CogPlatform/Mymou/commit/2e8200e21214d62de6fd79f2ee327730d72fdc04

Added to the choice phase Runnable(), the timer is now relative to when the choice phase starts. Thanks!
