### ISSUE TITLE
Abstract away NHP IDs

### ISSUE THREAD

**Issue by iandol** [jamesbutler01/Mymou#7]
In lots of places, your two subjects O and V are hardcoded (e.g. FolderManager, TaskExample). We'll need to refactor this so subject ids are not hardcoded, and are more flexibly assigned.

We are still designing our database, but ideally we should use a uuid for each subject, and that uuid gets used. When Mymou starts it queries the server or file and gets the subject list stored in a class. Then this subjects class can be queried and used when establishing what data to write / task to run.

I'm still a bit confused about how we pass round state more robustly, it seems we have to push around classes or try to use something like a singleton in each place. I'm sure there is a "better" way to design this (I've seen dependency injection discussed as a solution ([Dagger 2](https://www.raywenderlich.com/262-dependency-injection-in-android-with-dagger-2-and-kotlin) / [Koin](https://insert-koin.io) etc.), but it seems quite involved), so perhaps shuttling classes around is good enough for now...

**Comment by iandol** [comment]
See #9 for an example of our requirements for more robust subject IDs

**Comment by jamesbutler01** [comment]
Definitely needs doing, especially being able to specify number of subjects and then make appropriate number of folders, neural network sizes etc 

Agree would be good to have something like one UUID per subject which can then be used to tie everything together both on tablet and on backend server etc

**Comment by iandol** [comment]
I will make a SubjectManager class to handle loading the subject lists. It will offer methods to load from a JSON file or a database API. I'll model subjects with a Subject class, containing `uuid`, `name`, `comments` fields. SubjectManager will also be able to write to JSON from a new Subject object. I'll use the Java UUID library to create uuids (though they are somewhat overkill, we only probably need the first 8 characters)...

**Comment by jamesbutler01** [comment]
This now done, and NHPs are handled numerically so can be iterated over etc. FolderManager now makes appropriate folders for each NHP etc. Support added for up to 8 NHPs, and is trivial to add more (just need to add an additional go cue for each NHP.
