### ISSUE TITLE
Improve TaskManager to select among multiple tasks without recompiling

### ISSUE THREAD

**Issue by iandol** [jamesbutler01/Mymou#8]
Currently TaskManager is hardcoded to run a single task, and one must recompile to "choose" a different task to run. This should be rewritten so tasks can be selected from list. 

Currently the task field is assigned during object instantiation, which if there were lots of tasks is perhaps not efficient, so we should probably do this later in the code?

**Comment by jamesbutler01** [comment]
Yeah completely agree. I was thinking having a menu in MainMenu where user can select task, this selection can then be passed to TaskManager which then loads correct task from list (so all tasks would be hardcoded in TaskManager) ?

**Comment by iandol** [comment]
Yes, I think as a first step that will be fine. I'm happy to do this (I already refactored main_activity to use constraints as a learning exercise so can use this version of the layout to build on).

**Comment by jamesbutler01** [comment]
Now implemented
