### ISSUE TITLE
Face recognition for more subjects?

### ISSUE THREAD

**Issue by iandol** [jamesbutler01/Mymou#9]
We will have a chance to run some Mymou systems in group housing of 9 subjects. I wonder if the NN will handle 9 different subjects? What do you think?

**Comment by jamesbutler01** [comment]
It handled 4 with no issues and just ~100 photos per animal. No idea how it will scale with more animals and excited to find out. NNs should hopefully perform well at this task. It will definitely need some playing around with the hyperparameters. Will be relativity simple to add more layers/conv layers if needed, though this will dramatically increase calculation time and not recommended for doing synchronous facerecog

**Comment by iandol** [comment]
Thanks James! I close this and if we have trouble open a new issue...

**Comment by jamesbutler01** [comment]
I will update the NN code to allow you to specify number of subjects, but we wont be able to test anything until you have some training data, I don't have access to more than 4 subjects using the device here unfortunately.

**Comment by iandol** [comment]
Great! We are designing our Mymou holders, and will have no bars visible in the photos so I hope that will help a bit...

**Comment by jamesbutler01** [comment]
Ah nice. The OpenSCAD file is to scale so hopefully that is of some use or maybe you're just starting from scratch. Ours was made out of 8mm thick Acetal Copolmer sheet supplemented with metal brackets 3-6 mm thick, which was a nice trade off between integrity and weight that has held strong for 2 years now with virtually no wear and tear. We're making a new one soon entirely out of metal (aluminium i think) so we'll see how that goes.

**Comment by jamesbutler01** [comment]
Turns out I'd already adapted the NN to handle more subjects. Unfortunately I don't have permission to provide the example data from the extra 2 subjects that I used, so can't improve the current NN further without someone else contributing a selfie dataset.
